# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Install and configure Wordpress server
  hosts: wordpress_servers

  tasks:
    - include: tasks/mysql_server.yml
    - include: tasks/apache_server.yml
    - include: tasks/wordpress_server.yml

  handlers:
    - include: handlers/apache_service.yml
    - include: handlers/mysql_service.yml
    - include: handlers/zabbix_service.yml
