# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: (os=Ubuntu 14.04) Download WordPress dependencies
  apt: name=php5-gd,libssh2-php,php5-mysql,php5,libapache2-mod-php5,php5-mcrypt
  when: ansible_os_family == "Debian" and ansible_distribution_release == "trusty"

- name: Create WordPress user
  user: name={{ wordpress_user }} shell=/bin/bash

- name: Download WordPress
  get_url: 
    url: http://wordpress.org/latest.tar.gz 
    dest: "/home/{{ wordpress_user }}/latest.tar.gz"
  register: wordpress_download

- name: Extract WordPress files
  shell: "cd /home/{{ wordpress_user }} && tar xzvf latest.tar.gz"
  when: wordpress_download.changed

- name: Move WordPress files to Apache document root
  shell: "rsync -av /home/{{ wordpress_user }}/wordpress/ /var/www/html/"
  when: wordpress_download.changed
  notify:
    - apache_restart

- name: Set permissions for WordPress files
  file: src=/var/www/html/ dest=/var/www/html/ owner={{ wordpress_user }} group="www-data" recurse=yes
  when: wordpress_download.changed
  notify:
    - apache_restart

- name: Remove redundant WordPress folder and files
  file: path={{ item }} state=absent
  with_items:
    - /home/{{ wordpress_user }}/wordpress/
    - /var/www/html/index.html
  when: wordpress_download.changed

- name: Create WordPress database
  mysql_db: login_host={{ wordpress_db_host }} name={{ wordpress_db_name }} encoding='utf8'
  when: wordpress_download.changed
  notify:
    - mysql_restart

- name: Create WordPress database user
  mysql_user:
    host: "{{ wordpress_db_host }}"
    name: "{{ wordpress_db_username }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
  when: wordpress_download.changed
  notify:
    - mysql_restart

- name: Configure WordPress server
  template: 
    src: "files/{{ item }}"
    dest: "{{ item }}"
    owner: "{{ wordpress_user }}"
    group: www-data
    mode: 0644
  with_items:
    - /var/www/html/wp-config.php
  notify:
    - apache_restart
