# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: (os=Ubuntu 14.04) Install Zabbix server
  apt: name=zabbix-server-mysql
  when: ansible_os_family == "Debian" and ansible_distribution_release == "trusty"
  register: server_install

- name: Create Zabbix database
  mysql_db: login_host={{ zabbix_db_host }} name={{ zabbix_db_name }} encoding='utf8'
  when: server_install is defined and server_install.changed
  notify:
    - mysql_restart

- name: Create Zabbix database user
  mysql_user:
    host: "{{ zabbix_db_host }}"
    name: "{{ zabbix_db_username }}"
    password: "{{ zabbix_db_password }}"
    priv: "{{ zabbix_db_name }}.*:ALL"
  when: server_install is defined and server_install.changed
  notify:
    - mysql_restart

- name: Initialize Zabbix database
  mysql_db: name={{ zabbix_db_name }} state=import target=/usr/share/doc/zabbix-server-mysql/create.sql.gz
  when: server_install is defined and server_install.changed
  notify:
  - zabbix_server_start

- name: Configure Zabbix server
  template: src=files/{{ item }} dest={{ item }} owner=root group=zabbix mode=0640
  with_items:
    - /etc/zabbix/zabbix_server.conf
  notify:
  - zabbix_server_restart

- name: Start Zabbix server
  service: name=zabbix-server state=started enabled=yes
  when: server_install is defined and server_install.changed
