# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: (os=Ubuntu 14.04) Check Zabbix repositories
  stat: path=/etc/apt/sources.list.d/zabbix.list
  register: zabbix_repos_list
  when: ansible_os_family == "Debian" and ansible_distribution_release == "trusty"

- name: Download Zabbix release package
  get_url: 
    url: "http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+trusty_all.deb"
    dest: "/tmp/zabbix-release.deb"
  register: zabbix_release_deb
  when: zabbix_repos_list.stat.exists is defined and zabbix_repos_list.stat.exists == False

- name: (os=Ubuntu 14.04) Enable Zabbix repositories
  command: dpkg -i /tmp/zabbix-release.deb
  register: zabbix_repos
  when: zabbix_repos_list.stat.exists is defined and zabbix_repos_list.stat.exists == False

- name: (os=Ubuntu 14.04) Update repositories cache
  apt: update_cache=yes
  when: zabbix_repos.changed

- name: Remove Zabbix release package
  file: path=/tmp/zabbix-release.deb state=absent
  when: zabbix_release_deb.changed
