# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: (os=Ubuntu 14.04) Install Zabbix agent
  apt: name=zabbix-agent
  when: ansible_os_family == "Debian" and ansible_distribution_release == "trusty"

- name: Configure Zabbix agent
  template: src=files{{ item }} dest={{ item }}
  with_items:
    - /etc/zabbix/zabbix_agentd.conf
  notify: zabbix_agent_restart

- name: Enable and start Zabbix agent
  service: name=zabbix-agent state=started enabled=yes
